package:
  name: ora
  version: 0.2.0

about:
  home: https://github.com/alexhsamuel/ora
  license: BSD
  license_file: LICENSE

source:
  git_rev: 0.2.0
  git_url: https://github.com/alexhsamuel/ora.git

requirements:
  build:
    - numpy
    - python ==3.6*
    - setuptools
  run:
    - libgcc
    - numpy
    - python ==3.6*

build:
  script: python setup.py install

test:
  imports:
    - ora

