package:
  name: ora
  version: 0.3.1

about:
  home: https://github.com/alexhsamuel/ora
  license: BSD
  license_file: LICENSE

source:
  git_rev: v0.3.1
  git_url: https://github.com/alexhsamuel/ora.git

requirements:
  build:
    - numpy
    - python 3.6.*
    - setuptools
  run:
    - libgcc
    - python 3.6.*

build:
  script: make -j test-cxx; python setup.py install --single-version-externally-managed --record=record.txt

test:
  requires:
    - numpy
    - pytest
    - pytz
  imports:
    - ora
  commands:
    - pytest --pyargs ora

